import sys
import os
import pytest
import bcrypt

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Set dummy environment variables to allow server.py to import
os.environ["MONGO_URL"] = "mongodb://localhost:27017"
os.environ["DB_NAME"] = "test_db"
os.environ["JWT_SECRET"] = "test_secret"
os.environ["ADMIN_EMAIL"] = "admin@example.com"
os.environ["ADMIN_PASSWORD"] = "password"

from server import hash_password, verify_password

class TestPasswordHashing:
    def test_hash_password_returns_string(self):
        """Test that hash_password returns a string."""
        password = "MySecurePassword123!"
        hashed = hash_password(password)

        assert isinstance(hashed, str)
        assert hashed != password

    def test_hash_password_valid_bcrypt(self):
        """Test that hash_password generates a valid bcrypt string."""
        password = "MySecurePassword123!"
        hashed = hash_password(password)

        # Bcrypt hashes generated by python-bcrypt start with $2b$ and have length 60
        assert hashed.startswith("$2b$")
        assert len(hashed) == 60

        # Should be able to manually check it
        assert bcrypt.checkpw(password.encode("utf-8"), hashed.encode("utf-8"))

    def test_hash_password_salts_randomly(self):
        """Test that hashing the same password twice yields different results due to salting."""
        password = "MySecurePassword123!"
        hashed1 = hash_password(password)
        hashed2 = hash_password(password)

        assert hashed1 != hashed2
        # But both should be verifiable
        assert verify_password(password, hashed1) is True
        assert verify_password(password, hashed2) is True

    def test_verify_password_success(self):
        """Test that verify_password correctly identifies valid passwords."""
        password = "AnotherPassword456"
        hashed = hash_password(password)

        assert verify_password(password, hashed) is True

    def test_verify_password_failure(self):
        """Test that verify_password correctly rejects invalid passwords."""
        password = "AnotherPassword456"
        hashed = hash_password(password)

        assert verify_password("wrongpassword", hashed) is False
        assert verify_password("", hashed) is False
        assert verify_password(password + "a", hashed) is False

    def test_verify_password_invalid_hash(self):
        """Test that verify_password handles malformed or invalid hashes gracefully."""
        password = "SomePassword789"

        # Invalid hash format
        assert verify_password(password, "invalid_hash") is False

        # Empty hash
        assert verify_password(password, "") is False

        # Wrong bcrypt version/format but correct length
        assert verify_password(password, "$2a$12$SomeInvalidHashStringOfCorrectLen") is False
